### ISSUE TITLE
no sources being published on pypi index

### ISSUE THREAD

**Issue by shubhbapna** [DS4SD/deepsearch-glm#76]
We are trying to build deepsearch-glm from source downstream, however it looks like sdists aren't being published on the pypi index https://pypi.org/simple/deepsearch-glm/ ? Is it possible to start publishing those again?

**Comment by shubhbapna** [comment]
FYI we are trying to package Docling for [InstructLab](https://github.com/instructlab) and docling seems to have an installation time dependency on this package

**Comment by dolfim-ibm** [comment]
This has been fixed in https://github.com/DS4SD/deepsearch-glm/releases/tag/v0.23.0
