### ISSUE TITLE
Support building against system libraries

### ISSUE THREAD

**Issue by shubhbapna** [DS4SD/deepsearch-glm#78]
`deepsearch-glm` uses cmake's `ExternalProject_Add` feature to download 3rd dependencies at build time. The build system then vendors the 3rd binaries libraries into the wheel. We prefer to use system-provided libraries, so we can track the provenance of all dependencies. System libraries also allow us to address security issues without rebuilding all components.

Would it be possible to add a mode to use system-provided libraries via cmake `find_package()` or `pkgconfig`?

**Comment by dolfim-ibm** [comment]
Fixed in https://github.com/DS4SD/deepsearch-glm/releases/tag/v0.23.0
